// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import "./globals.css";
// import AuthControls from "@/app/components/auth-controls";

// export const metadata: Metadata = {
//   title: "Movie Tracker",
//   description: "Track your movies and TV shows",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <AuthControls />
//         {children}</body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import "./globals.css";
import AuthControls from "@/app/components/auth-controls";

export const metadata: Metadata = {
  title: "Movie Tracker",
  description: "Track your movies and TV shows",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black text-white">
        <header className="border-b border-white/10 bg-black/80">
          <div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
            <a
              href="/library"
              className="flex items-center gap-2 text-sm font-bold tracking-tight transition hover:text-gray-300 sm:text-base"
            >
              <span className="text-xl">🎬</span>
              <span>Movie Tracker</span>
            </a>

            <div className="flex shrink-0 items-center">
              <AuthControls />
            </div>
          </div>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
